# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da71a3bc340e2d559f62675c9204d4048735d56d35d90971b87c46d04120b657458f0761f422767226428125a683bc0f86b7e2ba64f388072ea23dd800770400

test:
  secret_key_base: 5b932b9143fbd9cbb01431df4bbea9365cab2b9714bd4055fba641fdc2a9bf0c3ccdf28ebf7301d9355bcfd23cc5773e44c6d474317055714f3c2206c38840f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
